### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by cooltrooper** [Swiftline/Swiftline#18]
Hi there,

I'm trying to include swiftline into a fresh Swift command line template Xcode project. I've built swiftline using carthage and included it in the "Link Binaries With Libraries" section to no avail.

```
dyld: Library not loaded: @rpath/Swiftline.framework/Versions/A/Swiftline
  Referenced from: /Users/cooltrooper/Library/Developer/Xcode/DerivedData/wlV1-fnrxshgimtnooghhhpyaripgrewy/Build/Products/Debug/wlV1
  Reason: image not found
```

Any tips?

**Comment by delebedev** [comment]
@cooltrooper could you please attach 2 screenshots: one for General tab with included framework visible, and another with Build Phases tab (I'm particularly interested in Embed Framework step)

**Comment by nsomar** [comment]
@cooltrooper I will close this issue since its been open for a while.
Please feel free to reopen if the issue persists :)
